---

- name: Clone application from git
    git:
          dest=/tmp/rails_test_project
              repo=https://github.com/cornaholic/rails_test_project.git

- name: Install bundler
    gem:
          name=bundler
              state=present

- name: Bundler Install
    bundler:
          chdir=/tmp/rails_test_project
              executable=~/bin/bundler
                  state=present
                      gemfile=Gemfile

- name: Create DB
    command: >
          chdir=/tmp/rails_test_project
              /home/ec2-user/bin/bundle exec rake db:create

- name: Migrate DB
    command: >
          chdir=/tmp/rails_test_project
              /home/ec2-user/bin/bundle exec rake db:migrate

- name: Seed DB
    command: >
          chdir=/tmp/rails_test_project
              /home/ec2-user/bin/bundle exec rake db:seed

- name: Start Rails Server
    command: >
          chdir=/tmp/rails_test_project
              rails server --binding=0.0.0.0
